### ISSUE TITLE
[Bug]: Rocblas errors out on fp16 gemm operations

### ISSUE THREAD

**Issue by IMbackK** [ROCm/Tensile#2044]
### Describe the bug
rocblas returns rocblas_status_internal_error when rocblas_hgemm is called on mi100:

```
rocBLAS error: Tensile solution found, but exception thrown for { a_type: "f16_r", b_type: "f16_r", c_type: "f16_r", d_type: "f16_r", compute_type: "f16_r", transA: 'N', transB: 'N', M: 256, N: 256, K: 64, alpha: 1, row_stride_a: 1, col_stride_a: 256, row_stride_b: 1, col_stride_b: 128, row_stride_c: 1, col_stride_c: 256, row_stride_d: 1, col_stride_d: 256, beta: 0, batch_count: 1, strided_batch: true, stride_a: 0, stride_b: 0, stride_c: 0, stride_d: 0, atomics_mode: atomics_allowed }
Alpha value 7.21875 doesn't match that set in problem: 1
This message will be only be displayed once, unless the ROCBLAS_VERBOSE_TENSILE_ERROR environment variable is set.
```

### To Reproduce
The issue can be repoduced with rocblas-bench:
rocblas-bench -f gemm -r h -m 256 -n 256 -k 64 --transposeA N --transposeB N

### Expected behavior
rocblas_hgemm should work for any valid input
### Environment

| Hardware | description |
|-----|-----|
| CPU |  MI100 |
| GPU |  EPYC 7402P|

| Software | version |
|-----|-----|
| rocm-core | v6.2.1 |
| rocblas | Self compiled @rocm-6.2.2 tag |

**Comment by ppanchad-amd** [comment]
Hi @IMbackK. Internal ticket has been created to investigate this issue. Thanks!

**Comment by IMbackK** [comment]
i just compiled rocblas with tensile as of 013a4b7cbe31146925f55c62149190c45a561640 and this issue seams to have been fixed in the git version.

**Comment by lubosz** [comment]
I am getting this when building Tensile in rocBLAS for `gfx1030` on Arch Linux, while it works when building the same source tree with the same CMake parameters from a ROCm Docker.

The issue can be reproduced using `rocblas-bench`
```
rocBLAS ((rocm-6.2.1))$ ./build/clients/staging/rocblas-bench \
  -f gemm_strided_batched_ex \
  --transposeA T \
  --transposeB N \
  -m 128 \
  -n 2 \
  -k 32 \
  --alpha 1.0 \
  --a_type f16_r \
  --lda 4096 \
  --stride_a 524288 \
  --b_type f16_r \
  --ldb 32 \
  --stride_b 64 \
  --beta 0.0 \
  --c_type f16_r \
  --ldc 128 \
  --stride_c 256 \
  --d_type f16_r \
  --ldd 128 \
  --stride_d 256 \
  --batch 40 \
  --compute_type f16_r \
  --algo 0
./build/clients/staging/rocblas-bench warning: --batch is deprecated, and --batch_count should be used instead.

rocBLAS-commit-hash: c6de03451d56f2d5997de4c1abb1cd81fb3cfd7c

Tensile-commit-hash: dbc2062dced66e4cbee8e0591d76e0a1588a4c70

Query device success: there are 1 devices
-------------------------------------------------------------------------------
Device ID 0 : AMD Radeon RX 6900 XT gfx1030
with 17.2 GB memory, max. SCLK 2660 MHz, max. MCLK 1000 MHz, memoryBusWidth 32 Bytes, compute capability 10.3
maxGridDimX 2147483647, sharedMemPerBlock 65.5 KB, maxThreadsPerBlock 1024, warpSize 32
-------------------------------------------------------------------------------


rocBLAS info: Time taken to complete rocBLAS library initialization is 438 milliseconds.

rocBLAS info: maximum library size per device is 0.392167 GB.

rocBLAS error: Tensile solution found, but exception thrown for { a_type: "f16_r", b_type: "f16_r", c_type: "f16_r", d_type: "f16_r", compute_type: "f16_r", transA: 'T', transB: 'N', M: 128, N: 2, K: 32, alpha: 1, row_stride_a: 1, col_stride_a: 4096, row_stride_b: 1, col_stride_b: 32, row_stride_c: 1, col_stride_c: 128, row_stride_d: 1, col_stride_d: 128, beta: 0, batch_count: 40, strided_batch: true, stride_a: 524288, stride_b: 64, stride_c: 256, stride_d: 256, atomics_mode: atomics_allowed }
Alpha value 7.21875 doesn't match that set in problem: 1
This message will be only be displayed once, unless the ROCBLAS_VERBOSE_TENSILE_ERROR environment variable is set.
rocBLAS status error: Expected rocblas_status_success, received rocblas_status_internal_error
```

More details:
https://gitlab.archlinux.org/archlinux/packaging/packages/rocblas/-/issues/2

This piece of code shows the actual problem:
```c
_Float16 one_f16 = 1.0;
_Float16 alpha_f16 = typedInputs.alpha;
printf("one_f16  : %f\n", static_cast<double>(one_f16));
printf("alpha_f16: %f\n", static_cast<double>(alpha_f16));

uint8_t* one_bytes = reinterpret_cast<uint8_t*>(&one_f16);
uint8_t* alpha_bytes = reinterpret_cast<uint8_t*>(&alpha_f16);
printf("one_bytes  : %02x %02x\n", one_bytes[0], one_bytes[1]);
printf("alpha_bytes: %02x %02x\n", alpha_bytes[0], alpha_bytes[1]);

printf("one_f16 equals alpha_f16: %d\n", one_f16 == alpha_f16);

// This only builds inside Tensile
std::stringstream inputValue;
inputValue << typedInputs.alpha;
printf("stringstream alpha: %s\n", inputValue.str().c_str());
```

### Output Tensile Docker (in `ContractionSolution.cpp`)

```
one_f16  : 1.000000
alpha_f16: 1.000000
one_bytes  : 00 3c
alpha_bytes: 00 3c
one_f16 equals alpha_f16: 1
stringstream alpha: 1
```

### Output rocblas Arch (in `tensile_host.cpp`)

```
one_f16  : 1.000000
alpha_f16: 1.000000
one_bytes  : 00 3c
alpha_bytes: 00 3c
one_f16 equals alpha_f16: 1
```

### Output Tensile Arch (in `ContractionSolution.cpp`)

This is the error.

```
one_f16  : 1.000000
alpha_f16: 2.406250
one_bytes  : 00 3c
alpha_bytes: 00 3c
one_f16 equals alpha_f16: 0
stringstream alpha: 7.21875
```

The incorrect value of the `alpha_f16` print changes every invocation in contrast to stringstream, which gives us the incorrect value from the error messages, `7.21875`.

**Comment by lubosz** [comment]
I am still getting this when building Tensile `4.43.0` (`013a4b7cbe31146925f55c62149190c45a561640`) in rocBLAS `rocm-6.2.1` for `gfx1030` on Arch Linux, while it works when building the same source tree with the same CMake parameters from a ROCm Docker (`rocm/pytorch:rocm6.2.2_ubuntu22.04_py3.10_pytorch_release_2.1.2`).

The issue can be reproduced using `rocblas-bench`
```
./build/clients/staging/rocblas-bench \
  -f gemm_strided_batched_ex \
  --transposeA T \
  --transposeB N \
  -m 128 \
  -n 2 \
  -k 32 \
  --alpha 1.0 \
  --a_type f16_r \
  --lda 4096 \
  --stride_a 524288 \
  --b_type f16_r \
  --ldb 32 \
  --stride_b 64 \
  --beta 0.0 \
  --c_type f16_r \
  --ldc 128 \
  --stride_c 256 \
  --d_type f16_r \
  --ldd 128 \
  --stride_d 256 \
  --batch_count 40 \
  --compute_type f16_r

rocBLAS-commit-hash: c6de03451d56f2d5997de4c1abb1cd81fb3cfd7c

Tensile-commit-hash: 013a4b7cbe31146925f55c62149190c45a561640

Query device success: there are 1 devices
-------------------------------------------------------------------------------
Device ID 0 : AMD Radeon RX 6900 XT gfx1030
with 17.2 GB memory, max. SCLK 2660 MHz, max. MCLK 1000 MHz, memoryBusWidth 32 Bytes, compute capability 10.3
maxGridDimX 2147483647, sharedMemPerBlock 65.5 KB, maxThreadsPerBlock 1024, warpSize 32
-------------------------------------------------------------------------------


rocBLAS info: Time taken to complete rocBLAS library initialization is 477 milliseconds.

rocBLAS info: maximum library size per device is 0.392167 GB.

rocBLAS error: Tensile solution found, but exception thrown for { a_type: "f16_r", b_type: "f16_r", c_type: "f16_r", d_type: "f16_r", compute_type: "f16_r", transA: 'T', transB: 'N', M: 128, N: 2, K: 32, alpha: 1, row_stride_a: 1, col_stride_a: 4096, row_stride_b: 1, col_stride_b: 32, row_stride_c: 1, col_stride_c: 128, row_stride_d: 1, col_stride_d: 128, beta: 0, batch_count: 40, strided_batch: true, stride_a: 524288, stride_b: 64, stride_c: 256, stride_d: 256, atomics_mode: atomics_allowed }
Alpha value 7.21875 doesn't match that set in problem: 1
This message will be only be displayed once, unless the ROCBLAS_VERBOSE_TENSILE_ERROR environment variable is set.
rocBLAS status error: Expected rocblas_status_success, received rocblas_status_internal_error
```

More details:
https://gitlab.archlinux.org/archlinux/packaging/packages/rocblas/-/issues/2

The below test results were done with the Tensile version shipped with rocBLAS 6.2.1.

This piece of code shows the actual problem:
```c
_Float16 one_f16 = 1.0;
_Float16 alpha_f16 = typedInputs.alpha;
printf("one_f16  : %f\n", static_cast<double>(one_f16));
printf("alpha_f16: %f\n", static_cast<double>(alpha_f16));

uint8_t* one_bytes = reinterpret_cast<uint8_t*>(&one_f16);
uint8_t* alpha_bytes = reinterpret_cast<uint8_t*>(&alpha_f16);
printf("one_bytes  : %02x %02x\n", one_bytes[0], one_bytes[1]);
printf("alpha_bytes: %02x %02x\n", alpha_bytes[0], alpha_bytes[1]);

printf("one_f16 equals alpha_f16: %d\n", one_f16 == alpha_f16);

// This only builds inside Tensile
std::stringstream inputValue;
inputValue << typedInputs.alpha;
printf("stringstream alpha: %s\n", inputValue.str().c_str());
```

### Output Tensile Docker (in `ContractionSolution.cpp`)

```
one_f16  : 1.000000
alpha_f16: 1.000000
one_bytes  : 00 3c
alpha_bytes: 00 3c
one_f16 equals alpha_f16: 1
stringstream alpha: 1
```

### Output rocblas Arch Linux (in `tensile_host.cpp`)

```
one_f16  : 1.000000
alpha_f16: 1.000000
one_bytes  : 00 3c
alpha_bytes: 00 3c
one_f16 equals alpha_f16: 1
```

### Output Tensile Arch Linux (in `ContractionSolution.cpp`)

This is the error.

```
one_f16  : 1.000000
alpha_f16: 2.406250
one_bytes  : 00 3c
alpha_bytes: 00 3c
one_f16 equals alpha_f16: 0
stringstream alpha: 7.21875
```

The incorrect value of the `alpha_f16` print changes every invocation in contrast to stringstream, which gives us the incorrect value from the error messages, `7.21875`.

So while still in rocBLAS the `_Float16` is interpreted correctly, but after arriving in Tensile it's garbage, even though it has the same byte value.

**Comment by babakpst** [comment]
Can you try --compute_type f32_r? It is more accurate and probably more efficient.

**Comment by lubosz** [comment]
@babakpst The same `rocblas-bench` invocation does succeed using `--compute_type f32_r`. The issue though is that this won't help with the compatibility of `llama.cpp` or `ollama`, since they try to use `f16_r`.

See
https://github.com/ggerganov/llama.cpp/issues/10234
https://github.com/ollama/ollama/issues/7564

**Comment by IMbackK** [comment]
Your results are quite strange
I configured rocblas with:

```
cmake
    -B build
    -S .
    -D CMAKE_BUILD_TYPE=None
    -D CMAKE_CXX_COMPILER=/opt/rocm/bin/hipcc
    -D CMAKE_TOOLCHAIN_FILE=toolchain-linux.cmake
    -D CMAKE_CXX_FLAGS="${CXXFLAGS} -fcf-protection=none"
    -D CMAKE_INSTALL_PREFIX=/opt/rocm
    -D CMAKE_PREFIX_PATH=/opt/rocm/llvm/lib/cmake/llvm
    -D amd_comgr_DIR=/opt/rocm/lib/cmake/amd_comgr
    -D BUILD_WITH_TENSILE=ON
    -D AMDGPU_TARGETS="gfx908:xnack-;gfx1030"
    -D Tensile_LIBRARY_FORMAT=msgpack
    -D Tensile_TEST_LOCAL_PATH="$srcdir/$_tensile_dir"
```

on archlinux using tensile 013a4b7cbe31146925f55c62149190c45a561640 and rocblas a203ccb76e3e15c47e9617d7761e8c0f9081e6f5 on arch linux and this works fine here, but i will reopen the bug for your sake for now.

**Comment by taylding-amd** [comment]
Hello @lubosz, thank you for reaching out. It appears that this issue may be specific to Arch Linux. Unfortunately, Arch Linux is not included in the official [ROCm compatibility matrix,](https://rocm.docs.amd.com/en/latest/compatibility/compatibility-matrix.html#) and the "official" ROCm package on Arch Linux is not maintained by AMD, so we can't guarantee its functionality. You might consider submitting this issue to the Arch Linux community or trying the ROCm Docker image as an alternative.

**Comment by svenstaro** [comment]
@lubosz wanna give rocm-llvm 6.2.4 in [extra-testing] a spin?

**Comment by IMbackK** [comment]
> @IMbackK I did use the same with the only difference setting `AMDGPU_TARGETS="gfx1030"` and using the internal Tensile of rocblas and I was able to reproduce the issue. I have done this in the PKGBUILD, so it should in theory produce a working build for you? https://gitlab.archlinux.org/lubosz/rocblas/-/tree/update-tensile

No it needs to be git rocblas AND tensile for it to work

also to be clear @taylding-amd  i can repoduce this issue on ubuntu when self compileing the 6.2.4 rocblas/tensile tag so its not related to arch linux persay but rather its a real bug in rocblas/tensile that depends on compiletime paramters.

**Comment by lubosz** [comment]
@svenstaro Yes I have tried rocm-llvm 6.2.4. I have the assumption that the problem does not lie in the PKGBUILD, since changing the tag to `rocm-6.1.0` fixes `rocm-llvm`. More details on the Arch issue.

@IMbackK Didn't consider rocblas git! that! Will give it a try.

**Comment by lubosz** [comment]
@IMbackK I could reproduce your results! I am able to produce a working ROCblas at https://github.com/ROCm/rocBLAS/commit/a203ccb76e3e15c47e9617d7761e8c0f9081e6f5 with Tensile git, even though using the latest `rocm-llvm` from Arch!
Although building rocBLAS git did require a couple of changes for me.
They were most related to Tensile, the same Tensile tag that worked with rocblas-6.2.2... seems that it changed how rocblas is providing the CMake config.

1. I now also need to set `CMAKE_C_COMPILER`, otherwise the Tensile build will error out. 
2. I now need to add `/opt/rocm/lib/llvm/bin/` to my `PATH`, since Tensile tried to resolve the compiler without an absolute path
3. I needed to set `-D BUILD_WITH_HIPBLASLT=OFF`, otherwise Tensile wanted a more recent `hipblaslt` than available in Arch, which wasn't a dependency before.
4. I needed to add `-I/opt/rocm/include` to the compiler flags in `TensileCreateLibrary.py`

Anyway, doing a hopefully easy bisect now and will backport a fix to the `rocblas-6.2.2` package.

**Comment by IMbackK** [comment]
Since this issue is now doubly confirmed to be fixed in rocm 6.3 (or whatever the next version will be called) im closeing it.

**Comment by lubosz** [comment]
FWIW this was a bug in rocblas all along.

I was able to bisect the fixing commit on rocBLAS git:
```
c6bc09073959a2881a701b88ae1ed9de469354f1 is the first new commit
commit c6bc09073959a2881a701b88ae1ed9de469354f1
Author: amcamd <andrew.chapman@gmail.com>
Date:   Mon Apr 29 15:06:12 2024 -0500

    remove mf16c flag as f16 intrinsics _cvtss_sh, _cvtsh_ss no longer used

 clients/benchmarks/CMakeLists.txt | 8 --------
 clients/gtest/CMakeLists.txt      | 4 ----
 clients/samples/CMakeLists.txt    | 2 --
 library/CMakeLists.txt            | 5 +----
 4 files changed, 1 insertion(+), 18 deletions(-)
```

https://github.com/ROCm/rocBLAS/commit/c6bc09073959a2881a701b88ae1ed9de469354f1

This commit removes the `-mf16c` build flag from several targets, including Tensile. This fixes the issue.
It works with several Tensile versions and is independent of the Tensile source. So it also works with Tensile at the `rocm-6.2.2` tag.

**Comment by IMbackK** [comment]
hmm that reaks of a compiler bug, maybe we should file against llvm

**Comment by svenstaro** [comment]
@lubosz great work! Wanna make an MR against the Arch package with the backport?

**Comment by lubosz** [comment]
@svenstaro Opened the MR before I posted my results here ;)
https://gitlab.archlinux.org/archlinux/packaging/packages/rocblas/-/merge_requests/2
